version: '3.8'

services:
  # 1. Serviço do Backend (Node.js Express)
  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile
    container_name: cogim-backend
    env_file:
      - .env.backend
    expose:
      - "3000" # Porta interna
    networks:
      - app-network

  # 2. Serviço do Frontend (Nginx Estático)
  frontend:
    build:
      context: . # Usa a raiz para aceder a 'admin/' e ficheiros soltos
      dockerfile: frontend/Dockerfile 
    container_name: cogim-frontend
    expose:
      - "80" # Porta interna do Nginx frontend
    networks:
      - app-network

  # 3. Serviço do Proxy Reverso (Nginx) - Ponto de Entrada Público
  proxy:
    image: nginx:alpine
    container_name: cogim-proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      # A porta 80 será a porta que o Render vai expor!
      - "80:80" 
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge